Feature/share popover
ZenUml/web-sequence pull request #586
Opened 2023-10-26 09:53 UTC by dontry

2023-10-27 01:53 UTC, MrCoder requested changes

2023-10-27 01:53 UTC, MrCoder commented on src/components/SharePanel.jsx
> +				{isLoading ?
Loading 状态可不可以只影响Copy Link那个Button。现在这样影响整个Panel，给用户的感觉响应太慢。用户看到静态内容，然后Copy Link稍微等一下是可以的，因为用户的注意力还没有立刻转移到那里。

2023-10-27 01:53 UTC, MrCoder commented on src/components/SharePanel.jsx
> +							<div className="preview" >
Preview的设计请参考这个页面上的那个Card： https://zenuml-demo.atlassian.net/wiki/spaces/DEMO/pages/511049729/Embed+ZenUML.cn

2023-10-31 11:28 UTC, MrCoder commented
@dontry Please resolve the conflict and update preview card according to https://github.com/ZenUml/web-app-laravel/pull/151

2023-10-31 11:29 UTC, MrCoder commented
Once it is ready, please remove the "Draft" status.

2023-11-02 11:08 UTC, dontry commented
> @dontry Please resolve the conflict and update preview card according to https://github.com/ZenUml/web-app-laravel/pull/151 

@MrCoder Can I remove all unecessary asyn/await from `app.tsx` file?

2023-11-04 04:26 UTC, MrCoder commented
> @MrCoder Can I remove all unecessary asyn/await from `app.tsx` file?
Sure

2023-11-04 04:33 UTC, MrCoder approved these changes

2023-11-04 04:34 UTC, merged